version: '3.1'

services:

  elasticsearch:
    container_name: 'elasticsearch'
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    restart: always
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    environment:
      - discovery.type=single-node
    networks:
      - root_docker-network
    volumes:
       - ./elasticsearch/config:/usr/share/elasticsearch/config

  kibana:
    container_name: 'kibana'
    image: docker.elastic.co/kibana/kibana:7.4.0
    restart: always
    ports:
      - 127.0.0.1:5601:5601
    environment:
      - ELASTICSEARCH_URL:'http://elasticsearch:9200'
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - root_docker-network

  logstash:
    container_name: 'logstash'
    image: docker.elastic.co/logstash/logstash:7.4.0
    restart: always
    ports:
      - 127.0.0.1:9600:9600
    networks:
      - root_docker-network
    volumes:
       - ./logstash/config:/usr/share/logstash/config

networks:
  root_docker-network:
    external: true
