version: '3.1'

services:

  elasticsearch:
    container_name: 'elasticsearch'
    image: elasticsearch:6.5.3
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    networks:
      - docker-network

  kibana:
    container_name: 'kibana'
    image: kibana:6.5.3
    restart: always
    ports:
      - "5601:5601"
    environment:
      #- discovery.type=single-node
      #- SERVER_NAME:'kibana:'
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5601
      - ELASTICSEARCH_URL:'http://elasticsearch:9200'
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - docker-network

  logstash:
    container_name: 'logstash'
    image: logstash:6.5.3
    restart: always
    ports:
      - "9600:9600"
    networks:
      - docker-network
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline/
      - ./logstash/settings/:/usr/share/logstash/config/

networks:
  docker-network:
    driver: bridge
